name: windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  workflow_dispatch:
#  pull_request:

jobs:
  perl:
    env:
      # some plugins still needs this to run their tests...
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: windows-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
      # # - id: 
      #   name: Setup DotNet@v1
      # #   uses: actions/setup-dotnet@v1

    # strategy:
    #   fail-fast: false
    #   matrix:
    #     perl-version:
    #       - 'latest'
    #       - '5.34'
    #       - '5.28'
    #       # - '5.16' No dzil
    #       # - '5.10' No dzil
    #
    # container:
    #   image: perldocker/perl-tester:${{ matrix.perl-version }}

      # # - id: 
      #   name: Checkout
      # #   uses: actions/checkout@v1
      - id: explore-tools
        name: Explore Tools
        run: |
          perl -V
          cpan -V
      - id: install-dzil
        name: Install Dist::Zilla
        # -T Do not test modules. Simply install them.
        run: |
          cpan -T Dist::Zilla
      - id: explore-dzil
        name: List Dist::Zilla and its dependencies
        run: |
          dir
          dir C:\Users
          dir .cpan
          dir .cpan\build
      # # - id: 
      #   name: Install Dependencies
      # #   #run: cpm install -g --no-test --show-build-log-on-failure --cpanfile cpanfile
      # #   run: cpm install -g --no-test --show-build-log-on-failure --cpanfile cpanfile
      # # - id: 
      #   name: Makefile.PL
      # #   run: perl Makefile.PL
      - id: install-dzil-authordeps
        name: Install Dist::Zilla Author Dependencies
        run: |
          dzil authordeps --missing --versions | \
            cpanm --verbose --force --notest || true
      - id: install-deps
        name: Install Dependencies
        run: |
          dzil listdeps --missing --develop --requires --recommends --suggests --version \
            | cpanm --verbose --force --notest || true
      - id: run-tests
        name: Run Tests
        run: |
          prove -lrv t
